### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by williamzerner** [AdroMine/Predicting-Fraud-in-Financial-Statements#1]
startServer() has been depleted. All links have been changed to https so xmlparsetree doesn't work. Is there anyway to fix it?

**Comment by AdroMine** [comment]
https://rdrr.io/cran/RSelenium/man/startServer.html
startServer has become defunct now. They recommend using rsDriver now. 
Also the layout for moneycontrol has changed significantly, so you will have to redo the full scraping part.
